FROM zaryob/sulin:minimal
MAINTAINER Suleyman POYRAZ

RUN cp /usr/share/baselayout/passwd /usr/share/baselayout/group /usr/share/baselayout/shadow /etc/
RUN inary ur && inary dc
RUN inary it -c system.base --ignore-conf --yes-all && inary dc
RUN inary cp

CMD [ "/bin/sh" ]
